entity_child_count = 2
entity_start_count = 3000

grid_width = 150
grid_height = 150

neural_network_hidden_layer_width = 10
neural_network_hidden_layer_depth = 3
neural_network_mutation_rate = 0.001

neural_network_connection_mutation_rate = 0.15
neural_network_connection_mutation_magnitude = 0.2

neural_network_structure_mutation_rate = 0.02

render_killzone_color = [150, 45, 0, 255]
render_background_color = [18, 22, 30, 255]
render_pixel_scale = 6

debug = false
