entity_child_count = 2
entity_start_count = 1000
grid_width = 200
grid_height = 200
neuron_connection_count = 4
neuron_fire_threshold = 1.0
neuron_signal_range = 4.0
render_killzone_color = [150, 75, 0, 255]
render_pixel_scale = 4
sim_generation_steps = 100
