# TODO: Move these to scenario
entity_start_count = 3000
entity_survivor_breed_rate = 0.25
entity_survivor_child_count = 4   # TODO: Should this just be derived from breed rate?


grid_width = 150
grid_height = 150


neural_network_hidden_layer_width = 10
neural_network_hidden_layer_depth = 3
neural_network_mutation_rate = 0.001

render_rad_zone_color = [150, 45, 0, 255]
render_background_color = [18, 22, 30, 255]
render_pixel_scale = 6


debug = false
