entity_child_count = 4
entity_start_count = 1000


grid_width = 150
grid_height = 150

neural_network_hidden_layer_width = 10
neural_network_hidden_layer_depth = 2
neural_network_mutation_rate = 0.25
neural_network_mutation_magnitude = 0.2

render_killzone_color = [150, 45, 0, 255]
render_background_color = [18, 22, 30, 255]
render_pixel_scale = 6
